# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mac Catalyst App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MQTT
  pod 'CocoaMQTT/WebSockets', '1.3.0-rc.1'

  # Pods for Firebase auth
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
end
